In [ ]:
import pandas as pd
import preprocessing as prep

# some text
that I want to share

In [14]:
df = pd.read_csv('yearly_income_train.csv')
prep.print_df_metadata(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26049 entries, 0 to 26048
Data columns (total 17 columns):
Unnamed: 0        26049 non-null int64
age               26049 non-null int64
workclass         26049 non-null object
fnlwgt            26049 non-null int64
education         26049 non-null object
education.num     26049 non-null int64
marital.status    26049 non-null object
occupation        26049 non-null object
relationship      26049 non-null object
race              26049 non-null object
sex               26049 non-null object
capital.gain      26049 non-null int64
capital.loss      26049 non-null int64
hours.per.week    26049 non-null int64
native.country    26049 non-null object
income            26049 non-null object
new_id_col        26049 non-null int64
dtypes: int64(8), object(9)
memory usage: 3.4+ MB
Column: Unnamed: 0  |  Type = int64  |  26049 Unique Values
	 Negatice Count = 0  |  NaN count = 0
Column: age  |  Type = int64  |  73 Unique Values
	 Negatice Count = 0  |  NaN count = 0
Column: workclass  |  Type = object  |  9 Unique Values
	workclass
	?                    1474
	Federal-gov           774
	Local-gov            1703
	Never-worked            7
	Private             18099
	Self-emp-inc          903
	Self-emp-not-inc     2020
	State-gov            1057
	Without-pay            12
	Name: new_id_col, dtype: int64
Column: fnlwgt  |  Type = int64  |  18433 Unique Values
	 Negatice Count = 0  |  NaN count = 0
Column: education  |  Type = object  |  16 Unique Values
	education
	10th             742
	11th             945
	12th             344
	1st-4th          130
	5th-6th          258
	7th-8th          521
	9th              416
	Assoc-acdm       851
	Assoc-voc       1112
	Bachelors       4275
	Doctorate        333
	HS-grad         8335
	Masters         1392
	Preschool         40
	Prof-school      468
	Some-college    5887
	Name: new_id_col, dtype: int64
Column: education.num  |  Type = int64  |  16 Unique Values
	 Negatice Count = 0  |  NaN count = 0
Column: marital.status  |  Type = object  |  7 Unique Values
	marital.status
	Divorced                  3590
	Married-AF-spouse           20
	Married-civ-spouse       11952
	Married-spouse-absent      339
	Never-married             8519
	Separated                  831
	Widowed                    798
	Name: new_id_col, dtype: int64
Column: occupation  |  Type = object  |  15 Unique Values
	occupation
	?                    1481
	Adm-clerical         2987
	Armed-Forces            8
	Craft-repair         3292
	Exec-managerial      3219
	Farming-fishing       804
	Handlers-cleaners    1094
	Machine-op-inspct    1592
	Other-service        2619
	Priv-house-serv       126
	Prof-specialty       3338
	Protective-serv       513
	Sales                2946
	Tech-support          749
	Transport-moving     1281
	Name: new_id_col, dtype: int64
Column: relationship  |  Type = object  |  6 Unique Values
	relationship
	Husband           10523
	Not-in-family      6667
	Other-relative      755
	Own-child          4074
	Unmarried          2771
	Wife               1259
	Name: new_id_col, dtype: int64
Column: race  |  Type = object  |  5 Unique Values
	race
	Amer-Indian-Eskimo      245
	Asian-Pac-Islander      819
	Black                  2484
	Other                   226
	White                 22275
	Name: new_id_col, dtype: int64
Column: sex  |  Type = object  |  2 Unique Values
	sex
	Female     8638
	Male      17411
	Name: new_id_col, dtype: int64
Column: capital.gain  |  Type = int64  |  117 Unique Values
	 Negatice Count = 0  |  NaN count = 0
Column: capital.loss  |  Type = int64  |  88 Unique Values
	 Negatice Count = 0  |  NaN count = 0
Column: hours.per.week  |  Type = int64  |  93 Unique Values
	 Negatice Count = 0  |  NaN count = 0
Column: native.country  |  Type = object  |  41 Unique Values
	native.country
	?                               465
	Cambodia                         15
	Canada                           93
	China                            60
	Columbia                         51
	Cuba                             76
	Dominican-Republic               58
	Ecuador                          24
	El-Salvador                      80
	England                          71
	France                           23
	Germany                         116
	Greece                           27
	Guatemala                        50
	Haiti                            34
	Honduras                         11
	Hong                             15
	Hungary                          11
	India                            77
	Iran                             32
	Ireland                          18
	Italy                            60
	Jamaica                          61
	Japan                            45
	Laos                             16
	Mexico                          497
	Nicaragua                        29
	Outlying-US(Guam-USVI-etc)       13
	Peru                             22
	Philippines                     151
	Poland                           50
	Portugal                         30
	Puerto-Rico                      92
	Scotland                         10
	South                            65
	Taiwan                           41
	Thailand                         15
	Trinadad&Tobago                  16
	United-States                 23364
	Vietnam                          53
	Yugoslavia                       12
	Name: new_id_col, dtype: int64
Column: income  |  Type = object  |  2 Unique Values
	income
	<=50K    19782
	>50K      6267
	Name: new_id_col, dtype: int64

In [8]:
id_col_name = "Unnamed: 0"
weight_col_name = "fnlwgt"
target_col_name = "income"
new_target_col = "income_weight"

df[new_target_col] = (1 - (df[target_col_name] == "<=50K") * 2) * df[weight_col_name]

df.drop([weight_col_name, target_col_name], axis=1, inplace=True)

target_col_name = new_target_col

In [8]:
id_col_name = "Unnamed: 0"
weight_col_name = "fnlwgt"
target_col_name = "income"
new_target_col = "income_weight"

df[new_target_col] = (1 - (df[target_col_name] == "<=50K") * 2) * df[weight_col_name]

df.drop([weight_col_name, target_col_name], axis=1, inplace=True)

target_col_name = new_target_col

In [15]:
df["capital_net"] = df["capital.gain"] - df["capital.loss"]
df.drop(["capital.gain","capital.loss"], axis = 1, inplace = True)

In [11]:
prep.count_value_pairs_between_columns(df, "education.num", "education")

(1, Preschool)          40
(2, 1st-4th)           130
(3, 5th-6th)           258
(4, 7th-8th)           521
(5, 9th)               416
(6, 10th)              742
(7, 11th)              945
(8, 12th)              344
(9, HS-grad)          8335
(10, Some-college)    5887
(11, Assoc-voc)       1112
(12, Assoc-acdm)       851
(13, Bachelors)       4275
(14, Masters)         1392
(15, Prof-school)      468
(16, Doctorate)        333
Name: new_col, dtype: int64

It is obvious that there's a 1-1 relation between these columns and hence one can be deprecated.

Now, assuming that `some-college` is a fancy name to `college dropout`, we group the education level according to their qualifications:
        `ARRIVED_AT_HIGH_SCHOOL`, `FINISHED_HiGH_SCHOOL`, `

In [19]:
age_col = df["age"]
df = df.copy()
min_age_bin = age_col.mi
for i in range (age_col.min() / 5, age_col.max() - 9, 5):
    df["age_" + str(i) + "_" + str(i+10)] = (i < age_col) & (age_col < (i + 10))
df

,Unnamed: 0,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,...,age_32_42,age_37_47,age_42_52,age_47_57,age_52_62,age_57_67,age_62_72,age_67_77,age_72_82,age_77_87
0,7339,23,?,191444,HS-grad,9,Never-married,?,Own-child,White,...,False,False,False,False,False,False,False,False,False,False
1,4515,55,Local-gov,98545,10th,6,Married-civ-spouse,Adm-clerical,Husband,White,...,False,False,False,True,True,False,False,False,False,False
2,27456,20,Private,238384,HS-grad,9,Never-married,Sales,Not-in-family,White,...,False,False,False,False,False,False,False,False,False,False
3,15796,27,?,175552,5th-6th,3,Married-civ-spouse,?,Wife,White,...,False,False,False,False,False,False,False,False,False,False
4,23242,88,Self-emp-not-inc,187097,Prof-school,15,Married-civ-spouse,Exec-managerial,Husband,White,...,False,False,False,False,False,False,False,False,False,False
5,31016,19,Local-gov,354104,HS-grad,9,Never-married,Adm-clerical,Own-child,White,...,False,False,False,False,False,False,False,False,False,False
6,30014,37,Private,314963,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,White,...,True,False,False,False,False,False,False,False,False,False
7,27282,45,Private,128378,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,Black,...,False,True,True,False,False,False,False,False,False,False
8,8764,50,Private,202296,Assoc-voc,11,Separated,Prof-specialty,Unmarried,White,...,False,False,True,True,False,False,False,False,False,False
9,26466,41,Private,207779,HS-grad,9,Separated,Other-service,Not-in-family,White,...,True,True,False,False,False,False,False,False,False,False
10,31087,39,Private,230356,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,...,True,True,False,False,False,False,False,False,False,False
11,31326,31,Self-emp-not-inc,44503,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,...,False,False,False,False,False,False,False,False,False,False
12,9061,33,Private,164748,Bachelors,13,Married-civ-spouse,Transport-moving,Husband,White,...,True,False,False,False,False,False,False,False,False,False
13,19097,37,Private,223433,HS-grad,9,Married-civ-spouse,Sales,Husband,White,...,True,False,False,False,False,False,False,False,False,False
14,20516,49,Private,233639,11th,7,Married-civ-spouse,Other-service,Husband,White,...,False,False,True,True,False,False,False,False,False,False
15,4715,69,Private,136218,11th,7,Never-married,Machine-op-inspct,Not-in-family,White,...,False,False,False,False,False,False,True,True,False,False
16,4904,34,Private,73585,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,...,True,False,False,False,False,False,False,False,False,False
17,15552,30,Private,381153,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,...,False,False,False,False,False,False,False,False,False,False
18,27197,43,Self-emp-not-inc,350387,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,...,False,True,True,False,False,False,False,False,False,False
19,14612,54,State-gov,32778,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,...,False,False,False,True,True,False,False,False,False,False
20,12882,33,Private,198452,Assoc-acdm,12,Divorced,Sales,Not-in-family,White,...,True,False,False,False,False,False,False,False,False,False
21,22160,49,Self-emp-not-inc,111066,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,...,False,False,True,True,False,False,False,False,False,False
22,23090,52,Private,168001,Masters,14,Divorced,Prof-specialty,Not-in-family,White,...,False,False,False,True,False,False,False,False,False,False
23,28794,25,State-gov,153534,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,...,False,False,False,False,False,False,False,False,False,False
24,31254,44,Private,202872,Assoc-acdm,12,Divorced,Prof-specialty,Not-in-family,White,...,False,True,True,False,False,False,False,False,False,False
25,7664,40,Private,120277,HS-grad,9,Never-married,Handlers-cleaners,Own-child,White,...,True,True,False,False,False,False,False,False,False,False
26,23178,37,Private,179088,Some-college,10,Divorced,Adm-clerical,Not-in-family,White,...,True,False,False,False,False,False,False,False,False,False
27,5897,38,Local-gov,255454,Bachelors,13,Separated,Prof-specialty,Unmarried,Black,...,True,True,False,False,False,False,False,False,False,False
28,5462,31,Private,127610,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,White,...,False,False,False,False,False,False,False,False,False,False
29,21856,39,Local-gov,149833,Bachelors,13,Divorced,Prof-specialty,Unmarried,White,...,True,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26019,9840,26,Private,159732,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,...,False,False,False,False,False,False,False,False,False,False
26020,11367,20,Private,124751,Some-college,10,Never-married,Priv-house-serv,Own-child,White,...,False,False,False,False,False,False,False,False,False,False
26021,8079,38,Private,296999,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,...,True,True,False,False,False,False,False,False,False,False
26022,21152,44,Local-gov,100479,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,...,False,True,True,False,False,False,False,False,False,False
26023,7774,31,Local-gov,190401,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,...,False,False,False,False,False,False,False,False,False,False
26024,26213,24,State-gov,330836,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,White,...,False,False,False,False,False,False,False,False,False,False
26025,14058,23,Private,263899,Some-college,10,Never-married,Adm-clerical,Own-child,Black,...,False,False,False,False,False,False,False,False,False,False
26026,4128,66,Self-emp-not-inc,167687,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,...,False,False,False,False,False,True,True,False,False,False
26027,13864,28,Private,250135,HS-grad,9,Never-married,Prof-specialty,Other-relative,White,...,False,False,False,False,False,False,False,False,False,False
26028,4508,76,Self-emp-not-inc,174309,Masters,14,Married-civ-spouse,Craft-repair,Husband,White,...,False,False,False,False,False,False,False,True,True,False
26029,17782,45,Private,189792,Masters,14,Married-civ-spouse,Sales,Husband,White,...,False,True,True,False,False,False,False,False,False,False
26030,30191,26,?,182332,Assoc-voc,11,Married-civ-spouse,?,Wife,White,...,False,False,False,False,False,False,False,False,False,False
26031,27828,28,Private,411587,Some-college,10,Never-married,Protective-serv,Own-child,White,...,False,False,False,False,False,False,False,False,False,False
26032,16322,55,Self-emp-inc,222615,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,...,False,False,False,True,True,False,False,False,False,False
26033,26767,20,Private,82777,Some-college,10,Never-married,Sales,Own-child,White,...,False,False,False,False,False,False,False,False,False,False
26034,4879,58,Self-emp-not-inc,87510,10th,6,Married-civ-spouse,Craft-repair,Husband,White,...,False,False,False,False,True,True,False,False,False,False
26035,30239,22,Private,228306,Some-college,10,Married-AF-spouse,Other-service,Wife,White,...,False,False,False,False,False,False,False,False,False,False
26036,22962,29,Private,138537,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,...,False,False,False,False,False,False,False,False,False,False
26037,20888,37,Private,25864,HS-grad,9,Separated,Prof-specialty,Unmarried,Amer-Indian-Eskimo,...,True,False,False,False,False,False,False,False,False,False
26038,8463,23,Private,218215,Assoc-acdm,12,Never-married,Other-service,Own-child,White,...,False,False,False,False,False,False,False,False,False,False
26039,8326,43,Private,212894,HS-grad,9,Divorced,Craft-repair,Other-relative,White,...,False,True,True,False,False,False,False,False,False,False
26040,30940,37,Private,29145,Assoc-voc,11,Never-married,Other-service,Not-in-family,White,...,True,False,False,False,False,False,False,False,False,False
26041,20127,28,Private,129460,9th,5,Never-married,Craft-repair,Not-in-family,White,...,False,False,False,False,False,False,False,False,False,False
26042,16367,30,Private,160634,Assoc-voc,11,Never-married,Craft-repair,Own-child,White,...,False,False,False,False,False,False,False,False,False,False
26043,23161,67,?,159542,5th-6th,3,Widowed,?,Unmarried,Black,...,False,False,False,False,False,False,True,False,False,False
26044,8607,62,Private,178745,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,...,False,False,False,False,False,True,False,False,False,False
26045,31019,33,Private,138142,Some-college,10,Separated,Other-service,Unmarried,Black,...,True,False,False,False,False,False,False,False,False,False
26046,25392,48,Private,39530,HS-grad,9,Divorced,Adm-clerical,Not-in-family,White,...,False,False,True,True,False,False,False,False,False,False
26047,14103,34,Private,96480,Some-college,10,Separated,Exec-managerial,Unmarried,White,...,True,False,False,False,False,False,False,False,False,False
26048,20951,28,Private,120471,HS-grad,9,Never-married,Transport-moving,Not-in-family,Other,...,False,False,False,False,False,False,False,False,False,False

In [22]:
df[df["workclass"] == "?"]

,Unnamed: 0,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,hours.per.week,native.country,income,capital_net
0,7339,23,?,191444,HS-grad,9,Never-married,?,Own-child,White,Male,40,United-States,<=50K,0
3,15796,27,?,175552,5th-6th,3,Married-civ-spouse,?,Wife,White,Female,40,Mexico,<=50K,0
69,3561,64,?,146272,Some-college,10,Married-civ-spouse,?,Husband,White,Male,15,United-States,<=50K,3411
72,32303,20,?,99891,Some-college,10,Never-married,?,Own-child,White,Female,30,United-States,<=50K,0
75,26206,65,?,106910,11th,7,Divorced,?,Not-in-family,Asian-Pac-Islander,Female,15,United-States,<=50K,0
81,6015,63,?,54851,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,40,United-States,<=50K,0
91,5794,19,?,263338,Some-college,10,Never-married,?,Own-child,White,Male,45,United-States,<=50K,0
111,17759,54,?,410114,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,40,United-States,<=50K,0
160,24565,17,?,48751,11th,7,Never-married,?,Own-child,Black,Female,40,United-States,<=50K,0
184,25078,20,?,358783,Some-college,10,Never-married,?,Own-child,White,Female,35,United-States,<=50K,0
192,25267,21,?,140012,Some-college,10,Never-married,?,Own-child,White,Male,20,United-States,<=50K,0
203,12372,17,?,406920,10th,6,Never-married,?,Own-child,White,Male,40,United-States,<=50K,0
222,3738,28,?,303674,HS-grad,9,Married-civ-spouse,?,Wife,White,Female,20,United-States,<=50K,3103
253,8319,60,?,204486,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,8,United-States,>50K,0
273,6778,22,?,35448,HS-grad,9,Married-civ-spouse,?,Wife,White,Female,22,United-States,<=50K,0
295,30176,52,?,244214,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,35,United-States,<=50K,0
318,18348,21,?,262062,Some-college,10,Never-married,?,Own-child,White,Female,40,United-States,<=50K,0
367,9232,62,?,97231,Some-college,10,Married-civ-spouse,?,Wife,White,Female,1,United-States,<=50K,0
393,4813,17,?,80077,11th,7,Never-married,?,Own-child,White,Female,20,United-States,<=50K,0
402,2012,49,?,271346,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,60,United-States,>50K,15024
414,5014,27,?,90270,Assoc-acdm,12,Married-civ-spouse,?,Own-child,Amer-Indian-Eskimo,Male,40,United-States,<=50K,0
431,10465,64,?,140237,Preschool,1,Married-civ-spouse,?,Husband,White,Male,40,United-States,<=50K,0
433,26359,52,?,318351,Some-college,10,Married-civ-spouse,?,Wife,White,Female,40,United-States,>50K,0
440,27088,18,?,91670,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Female,40,United-States,<=50K,0
450,15509,17,?,262196,10th,6,Never-married,?,Own-child,White,Male,8,United-States,<=50K,0
464,18827,38,?,181705,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,24,United-States,<=50K,0
501,11840,22,?,335453,Some-college,10,Never-married,?,Own-child,White,Female,16,United-States,<=50K,0
526,28830,44,?,91949,HS-grad,9,Never-married,?,Unmarried,Black,Female,40,United-States,<=50K,0
541,25808,43,?,218558,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,40,United-States,<=50K,0
563,7368,60,?,191024,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,40,United-States,<=50K,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25565,19912,46,?,148489,HS-grad,9,Married-spouse-absent,?,Not-in-family,Asian-Pac-Islander,Male,40,Philippines,<=50K,0
25621,14207,54,?,156877,HS-grad,9,Divorced,?,Not-in-family,White,Male,20,United-States,<=50K,0
25627,1614,58,?,266792,Some-college,10,Married-civ-spouse,?,Husband,White,Male,40,United-States,>50K,99999
25651,25743,60,?,139391,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,42,United-States,<=50K,0
25656,31276,17,?,172145,10th,6,Never-married,?,Own-child,Black,Female,40,United-States,<=50K,0
25661,18341,26,?,130832,Bachelors,13,Never-married,?,Unmarried,White,Female,10,United-States,<=50K,0
25703,16727,24,?,26671,HS-grad,9,Never-married,?,Other-relative,Amer-Indian-Eskimo,Female,40,United-States,<=50K,0
25711,27902,19,?,43739,HS-grad,9,Never-married,?,Own-child,White,Male,40,United-States,<=50K,0
25723,8417,31,?,345497,10th,6,Married-civ-spouse,?,Husband,White,Male,40,United-States,<=50K,0
25725,13162,17,?,210547,10th,6,Never-married,?,Own-child,White,Male,40,United-States,<=50K,0
25749,2340,64,?,159938,HS-grad,9,Divorced,?,Not-in-family,White,Male,40,United-States,>50K,8614
25752,25809,20,?,189740,Some-college,10,Never-married,?,Own-child,White,Female,32,United-States,<=50K,0
25780,20525,60,?,41517,11th,7,Married-spouse-absent,?,Unmarried,Black,Female,20,United-States,<=50K,0
25784,11078,81,?,162882,HS-grad,9,Divorced,?,Not-in-family,White,Female,35,United-States,<=50K,0
25845,6502,66,?,112871,11th,7,Never-married,?,Not-in-family,White,Male,30,United-States,<=50K,0
25846,17940,19,?,131982,Some-college,10,Never-married,?,Own-child,White,Male,40,United-States,<=50K,0
25850,7640,28,?,37215,Bachelors,13,Never-married,?,Own-child,White,Male,45,United-States,<=50K,0
25868,7648,29,?,315026,HS-grad,9,Divorced,?,Unmarried,White,Female,40,United-States,<=50K,0
25870,20429,33,?,192644,HS-grad,9,Never-married,?,Not-in-family,White,Male,40,United-States,<=50K,0
25894,24638,31,?,76198,HS-grad,9,Separated,?,Own-child,White,Female,20,United-States,<=50K,0
25897,14246,18,?,179484,12th,8,Never-married,?,Own-child,Other,Male,40,United-States,<=50K,0
25911,21256,29,?,256211,1st-4th,2,Never-married,?,Own-child,Asian-Pac-Islander,Male,40,Philippines,<=50K,0
25944,3501,74,?,340939,9th,5,Married-civ-spouse,?,Husband,White,Male,40,United-States,<=50K,3471
25965,24522,36,?,168223,Bachelors,13,Never-married,?,Own-child,White,Female,40,United-States,<=50K,0
25977,17971,18,?,171088,Some-college,10,Never-married,?,Own-child,White,Female,40,United-States,<=50K,0
25992,31900,35,?,35854,Some-college,10,Never-married,?,Own-child,White,Female,40,United-States,<=50K,0
25997,13411,22,?,289984,Some-college,10,Never-married,?,Not-in-family,Black,Female,25,United-States,<=50K,0
26016,4176,90,?,256514,Bachelors,13,Widowed,?,Other-relative,White,Female,10,United-States,<=50K,991
26030,30191,26,?,182332,Assoc-voc,11,Married-civ-spouse,?,Wife,White,Female,40,United-States,<=50K,0
26043,23161,67,?,159542,5th-6th,3,Widowed,?,Unmarried,Black,Female,40,United-States,<=50K,0

In [24]:
df[((df["marital.status"] == "Wife") & (df["sex"] == "Male")) | ((df["marital.status"] == "Husband") & (df["sex"] == "Female"))]

Empty DataFrame
Columns: [Unnamed: 0, age, workclass, fnlwgt, education, education.num, marital.status, occupation, relationship, race, sex, hours.per.week, native.country, income, capital_net]
Index: []

In [31]:
df[df["marital.status"] == "Husband"]

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
26019    False
26020    False
26021    False
26022    False
26023    False
26024    False
26025    False
26026    False
26027    False
26028    False
26029    False
26030    False
26031    False
26032    False
26033    False
26034    False
26035    False
26036    False
26037    False
26038    False
26039    False
26040    False
26041    False
26042    False
26043    False
26044    False
26045    False
26046    False
26047    False
26048    False
Name: marital.status, Length: 26049, dtype: bool

In [ ]:
reg = XGBRegressor()
    param_grid = {
        'max_depth': list(range(2, 20)),
        'learning_rate': 10. ** (np.array(range(-10,0) )/ 2.),
        'subsample': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
        'colsample_bytree': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
        'colsample_bylevel': [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
        'min_child_weight': [0.5, 1.0, 3.0, 5.0, 7.0, 10.0],
        'gamma': [0, 0.25, 0.5, 1.0],
        'reg_lambda': [0.1, 1.0, 5.0, 10.0, 50.0, 100.0],
        'n_estimators': list(range(10, 300, 30))}

    fit_params = {'eval_set': [fitter.get_valudation_data()]}

    rs_regr = RandomizedSearchCV(reg, param_grid, n_iter=20, refit=True, random_state=42)

    pred = fitter.fit_and_predict(rs_regr, **fit_params)
    new_fit = fitter.get_mse_with(pred)